# Funding links (uncomment and add your usernames to enable)
# github: [your-username]
# patreon: your-patreon-username
# open_collective: your-oc-username
# ko_fi: your-ko-fi-username
# buy_me_a_coffee: your-username
# custom: ["https://your-website.com/donate"]
